
sequenceDiagram
    participant Teacher
    participant TeacherView
    participant TeacherLessonController
    participant TeacherService
    participant TeacherRepository
    participant Database

    Teacher->>+TeacherView: 2.1. Ấn nút sửa nội dung
    TeacherView-->>-Teacher: 2.2. Chuyển đến trang sửa nội dung bài học
    Teacher->>+TeacherView: 2.3. Sửa nội dung bài học
    Teacher->>+TeacherView: 2.4. Nhấn nút "Lưu"
    TeacherView->>+TeacherLessonController: 2.5.1. Gửi id bài học
    TeacherLessonController->>TeacherService: 2.5.2. UpdateLesson()
    alt ServiceValidate()
        TeacherService->>+TeacherRepository: 2.5.3. UpdateLessonByIdAsync()
        TeacherRepository->>+Database: 2.5.4. executeQuery()

        Database-->>-Teacher: 2.5.5.1 Cập nhật nội dung buổi học thành công
    else invalid
        Database-->>-Teacher: 2.5.5.2.throw exception
    end

