
sequenceDiagram
    participant Teacher
    participant TeacherView
    participant TeacherTestController
    participant TeacherService
    participant TeacherRepository
    participant Database

    Teacher->>TeacherView: 2.1. Ấn nút sửa bài kiểm tra
    TeacherView-->>Teacher: 2.2. Chuyển đến trang sửa bài kiểm tra
    Teacher->>TeacherView: 2.3. Sửa nội dung bài kiểm tra
    Teacher->>TeacherView: 2.4. Nhấn nút "Lưu"
    TeacherView->>TeacherTestController: 2.5.1. Gửi id bài kiểm tra
    TeacherTestController->>TeacherService: 2.5.2. UpdateTest()
    alt ServiceValidate()
        TeacherService->>TeacherRepository: 2.5.3. UpdateTestByIdAsync()
        TeacherRepository->>Database: 2.5.4. executeQuery()

        Database-->>Teacher: 2.5.5. return result
    else invalid
         Database-->>Teacher: 2.5.6.2.throw exception
    end

