
sequenceDiagram
    participant Admin
    participant AdminView
    participant AdminController
    participant AdminService
    participant AdminRepository
    participant Database

    Admin->>AdminView:  1. Chọn tạo người dùng mới
    AdminView-->>Admin: 2. Yêu cầu nhập dữ liệu
    Admin->>AdminView: 3. Nhập dữ liệu và nhấp nút tạo
    
    AdminView->>AdminController: 4. Gửi dữ liệu 
    AdminController->>AdminService: 4.1. Gửi dữ liệu
    AdminService->>AdminService: Kiểm tra dữ liệu

    alt valid
        AdminService->>AdminRepository: 4.2.1.1 CreateUser()
        AdminRepository->>Database: 4.2.1.2 executeQuery()
        
        Database-->>AdminRepository: 4.2.1.3 return user with id
        AdminRepository-->>AdminService: 4.2.1.4 return User entity
        AdminService-->>AdminController: 4.2.1.5 return User entity
        AdminController-->>AdminView: 4.2.1.6 return User entity
        AdminView-->>Admin: 5.1. Tạo tài khoản thành công
    else invalid
        AdminService-->>AdminController: 4.2.2.1 throw exception
        AdminController-->>AdminView: 4.2.2.2 throw exception
        AdminView-->>Admin: 5.2. Thông báo lỗi
    end
