
sequenceDiagram
    participant Admin
    participant AdminView
    participant AdminController
    participant UserService
    participant UserRepository
    participant Database

    Admin->>AdminView: 1. Vào menu quản lý giáo viên
    AdminView-->>Admin: 2. Trả về danh sách giáo viên
    Admin->>AdminView: 3. Nhấn chỉnh sửa giáo viên
    AdminView-->>Admin: 4. Hiện modal thông tin giáo viên
    Admin->>AdminView: 5. Ấn nút "Đổi mật khẩu"
    
    AdminView->>AdminController: 6.1. Gửi dữ liệu về server
    AdminController->>UserService: 6.2. UpdateUserService()
    UserService->>UserService: 6.3. Kiểm tra dữ liệu

    alt valid
        UserService->>UserRepository: 6.4.1.1. UpdateUserInfo()
        UserRepository->>Database: 6.4.1.2. executeQuery()
        
        Database-->>AdminView: 6.4.1.3. return user with id
        AdminView-->>Admin: 6.4.1.4. Thông báo đổi mật khẩu thành công
    else invalid
        UserService-->>AdminView: 6.4.2.1. throw exception
        AdminView-->>Admin: 6.4.2.2. Thông báo lỗi
    end