sequenceDiagram
    participant Student
    participant StudentView
    participant StudentController
    participant StudentService
    participant StudentRepository
    participant Database

    Student->>StudentView: 1.Chọn lớp học
    StudentView->>StudentController: 2.1. Gửi id lớp học
    StudentController->>StudentService: 2.2. Gửi id lớp học
    StudentService->>StudentRepository: 2.3. GetLessonByClassroomId()
    StudentRepository->>Database: 2.4. executeQuery()

    Database-->>StudentView: 2.5. Render list lessons by classroom
    
    Student->>StudentView: 3. Click "xem bài giảng"
    StudentView->>StudentController: 4.1. Gửi id lesson
    StudentController->>StudentService: 4.2. Gửi id lesson
    StudentService->>StudentRepository: 4.3. GetLectureByLessonId()
    StudentRepository->>Database: 4.4. executeQuery()

    Database-->>StudentView: 4.5. Render lecture


