%%# Xoá khoá học

sequenceDiagram
    participant Staff
    participant StaffView
    participant StaffController
    participant StaffService
    participant StaffRepository
    participant Database

    Staff->>StaffView: 1. Chọn nút "Xoá" khoá học
    Staff->>StaffView: 2. Xác nhận "Xoá" khoá học
    
    StaffView->>StaffController: 3.1. Gửi yêu cầu xoá khoá học
    StaffController->>StaffService: 3.2. deleteCourseById()
    StaffService->>StaffRepository: 3.3. DeleteCourseByIdAsync()
    StaffRepository->>Database: 3.4. executeQuerry()
    Database-->>StaffRepository: 3.5. return result
    StaffRepository-->>StaffController: 3.6. delete success
    StaffController-->>StaffView: 3.7. render delete success
    
