sequenceDiagram
    participant Staff
    participant StaffView
    participant StaffController
    participant StaffService
    participant StaffRepository
    participant Database

    Staff->>StaffView: 1. Click "Thêm khóa học mới"
    StaffView-->>Staff: 2. Yêu cầu nhập dữ liệu
    Staff->>StaffView: 3. Nhập thông tin và nhấn "Tạo"
    StaffView->>StaffController: 4.1. Gửi dữ liệu
    StaffController->>StaffService: 4.2. Gửi dữ liệu
    StaffService->>StaffService: 4.3. Kiểm tra dữ liệu
    alt valid
        StaffService->>StaffRepository: 4.4.1.1. CreateCourse()
        StaffRepository->>Database: 4.4.1.2. executeQuery()
        Database-->>StaffRepository: 4.4.1.3. Return course with id
        StaffRepository-->>StaffController: 4.4.1.4. create course success
        StaffController-->>StaffView: 4.4.1.5. render success view
    else invalid
        StaffService-->>StaffView: 4.4.2.1. Throw exception
    end