sequenceDiagram
    participant Staff
    participant StaffView
    participant StaffController
    participant StaffService
    participant StaffRepository
    participant Database

    Staff->>StaffView: 1. Click "Thêm khóa học mới"
    StaffView-->>Staff: 2. Yêu cầu nhập dữ liệu
    Staff->>StaffView: 3. Nhập thông tin và nhấn "Tạo"
    StaffView->>StaffController: 4. Gửi dữ liệu
    StaffController->>StaffService: 4.1. Gửi dữ liệu
    StaffService->>StaffService: Kiểm tra dữ liệu
    alt valid
        StaffService->>StaffRepository: 4.2.1.1. CreateCourse()
        StaffRepository->>Database: 4.2.1.2. executeQuery()
        Database-->>StaffRepository: 4.2.1.3. Return course with id
        StaffRepository-->>StaffView: 4.2.1.4. Return course entity
        StaffView-->>Staff: 4.2.1.5. Thông báo tạo khóa học thành công
    else invalid
        StaffService-->>Staff: 4.2.2 Throw exception
    end