%%# chỉnh sửa khoá học

sequenceDiagram
    participant Staff
    participant StaffView
    participant StaffController
    participant StaffService
    participant StaffRepository
    participant Database

    Staff->>StaffView: 1. Chọn nút "Sửa" khoá học cần sửa thông tin

    Staff->>StaffView: 2. Nhập thông tin mới cần sửa
    Staff->>StaffView: 3. Click nút lưu
    StaffView->>StaffController: 4.1. Gửi yêu cầu chỉnh sửa khoá học
    StaffController->>StaffService: 4.2. updateCourse()
    StaffService->>StaffRepository: 4.3. UpdateCourserByIdAsync()
    StaffRepository->>Database: 4.4. executeQuerry()

    
    Database-->>StaffRepository: 4.5. return result
    StaffRepository-->>StaffController: 4.6. change success
    StaffController-->>StaffView: 4.7. render change success
    
