%%# chỉnh sửa thông tin học viên

sequenceDiagram
    participant Staff
    participant StaffView
    participant StaffController
    participant StaffService
    participant StaffRepository
    participant Database

    Staff->>StaffView:  1. Chọn nút "Sửa" học viên cần sửa thông tin

    Staff->>StaffView: 2. Nhập thông tin mới cần sửa
    Staff->>StaffView: 3. Click nút lưu
    StaffView->>StaffController: 3.1 Gửi yêu cầu chỉnh sửa học viên
    StaffController->>StaffService: 3.2 UpdateUser()
    StaffService->>StaffRepository: 3.3 UpdateUserByIdAsync()
    StaffRepository->>Database: 3.4 executeQuerry()

    
    Database-->>StaffRepository: 3.5 return result
    StaffRepository-->>StaffController: 3.6 change success
    StaffController-->>StaffView: 3.7 render change success
    

