
sequenceDiagram
    participant Staff
    participant StaffView
    participant StaffController
    participant StaffService
    participant StaffRepository
    participant Database

    Staff->>StaffView:  1. Chọn tạo lớp học mới
    StaffView-->>Staff: 2. Yêu cầu nhập dữ liệu
    Staff->>StaffView: 3. Nhập dữ liệu và nhấp nút tạo
    
    StaffView->>StaffController: 4.1. Gửi dữ liệu
    StaffController->>StaffService: 4.2. Gửi dữ liệu
    StaffService->>StaffService: Check data()

    alt valid
        StaffService->>StaffRepository: 4.2.1.1 CreateClassroom()
        StaffRepository->>Database: 4.2.1.2 executeQuery()
        Database-->>StaffView:: 4.2.1.3 return result
        StaffView-->>Staff: 5.1. Tạo lớp học thành công 
    else invalid
        StaffService-->>StaffController: 4.2.2.1 throw exception
        StaffController-->>StaffView: 4.2.2.2 throw exception
        StaffView-->>Staff: 5.2. Thông báo lỗi
    end

