
sequenceDiagram
    participant Staff
    participant StaffView
    participant StaffController
    participant StaffService
    participant StaffRepository
    participant Database

    Staff->>StaffView:  1. Chọn lớp cần thêm học viên
    StaffView->>StaffController: 2.1. Gửi id lớp học
    StaffController->>StaffService: 2.2. Lấy dữ liệu lớp học
    StaffService->>StaffRepository: 2.3. Lấy dữ liệu lớp học
    StaffRepository->>Database: 2.4. excuteQuery()
    Database -->> StaffRepository: 2.5. return List<Student>
    StaffRepository -->> StaffView: 2.6 return List<Student>
    Staff->>StaffView: 3. Ấn nút thêm học viên và chọn học viên
    StaffView->>StaffView: Check học viên đã có trong lớp học chưa


    alt valid
        StaffView->>StaffController: 4.1. Gửi dữ liệu
        StaffController->>StaffService: 4.2. Gửi dữ liệu
        StaffService->>StaffRepository: 4.3 Cập nhật lớp học
        StaffRepository->>Database: 4.4 executeQuery()
        Database-->>StaffView:: 4.5 return result
        StaffView-->>Staff: 5.1. Chỉnh sửa thành công 
    else invalid
 
        StaffView-->>Staff: Thông báo đã có học viên trong lớp 
    end

